### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AF_PACKET'

### ISSUE THREAD

**Issue by freetest** [OffensivePython/Nscan#10]
AttributeError: 'module' object has no attribute 'AF_PACKET'

**Comment by freetest** [comment]
Traceback (most recent call last):
  File "nscan.py", line 111, in <module>
    options = parser.parse_args()
  File "/Users/123/tools/Nscan/latest/startup.py", line 46, in parse_args
    ifname, ifaddr, ifmac, gateway = get.Network()
  File "/Users/123/tools/Nscan/latest/get.py", line 79, in Network
    sniff = socket.socket(socket.AF_PACKET,
AttributeError: 'module' object has no attribute 'AF_PACKET'

**Comment by bluescity** [comment]
some, meiby it's see only run in linux
