### ISSUE TITLE
Version of Python

### ISSUE THREAD

**Issue by tektengu** [OffensivePython/Nscan#8]
I am running python 2.7.5 on a Mac Mavericks. I do not see what version of python is required and when I do:

chmod +x nscan.py
./nscan.py

I get:
./nscan.py 
Traceback (most recent call last):
  File "./nscan.py", line 110, in <module>
    options = parser.parse_args()
  File "/Users/mindninja/Downloads/nscan/Nscan/stable/startup.py", line 44, in parse_args
    ifname, ifaddr, ifmac, gateway = get.Network()
  File "/Users/mindninja/Downloads/nscan/Nscan/stable/get.py", line 80, in Network
    sniff = socket.socket(socket.AF_PACKET,
AttributeError: 'module' object has no attribute 'AF_PACKET'

**Comment by OffensivePython** [comment]
Mac OS doesn't support raw sockets
