### ISSUE TITLE
No such device

### ISSUE THREAD

**Issue by simith003** [OffensivePython/Nscan#9]
Scanning [192.168.0.0 -> 192.169.0.0](65536 hosts/2 ports)
[MAIN] Starting the scan (Fri Oct 16 14:16:29 2015)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/nike/Nscan/latest/probe.py", line 186, in send
    sock.sendto(packet, (dec2dot(target), 0)) # self.ifname
error: [Errno 19] No such device

**Comment by Vikec** [comment]
Same problem

**Comment by go-spider** [comment]
can you resolve this issue?????
can or cannot!?

**Comment by Vikec** [comment]
no i use masscan now

**Comment by go-spider** [comment]
wise choice.

**Comment by fsxchen** [comment]
I have the same problem.

**Comment by l9c** [comment]
Same problem

**Comment by matthiasnehls** [comment]
me too

**Comment by wermaxta** [comment]
Same problem

**Comment by jwlyn** [comment]
Same problem

**Comment by LetUsFsck** [comment]
Same issue. 
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet XX.XX.XX.2  netmask 255.255.255.0  broadcast XX.XX.XX.255
        inet6 feXXX  prefixlen 64  scopeid 0x20<link>
        ether XX:XX:XX:a5:f9  txqueuelen 10000  (Ethernet)
        RX packets 802278871  bytes 57701647634 (53.7 GiB)
        RX errors 0  dropped 23  overruns 0  frame 0
        TX packets 14738547038  bytes 961101253167 (895.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 18  

eno1:nscan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet XX.XX.XX.3  netmask 255.255.0.0  broadcast XX.XX.255..255
        ether XX:XX:XX:a5:f9  txqueuelen 10000  (Ethernet)
        device interrupt 18  

Linux linuxmachine 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TachiuLam** [comment]
same problem
